-- RCP BMW Servie 0x22 Script
-- Version, <version>
-- Copyright (c) 2023 The SECRET Ingredient!
-- GNU General Public License v3.0
--
-- Select BMW OBD Service 0x22 PID Maps Available at
-- https://thesecretingredient.neocities.org
--
